# Generated by Django 5.2.3 on 2025-06-12 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='equipments/')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FarmHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('context', models.TextField()),
            ],
            options={
                'verbose_name': 'Farm History',
                'verbose_name_plural': 'Farm Histories',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('context', models.TextField()),
                ('image', models.ImageField(upload_to='manufacturing/')),
            ],
            options={
                'verbose_name': 'Manufacturing',
                'verbose_name_plural': 'Manufacturing',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='news/')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_team/')),
            ],
            options={
                'verbose_name': 'Our Team',
                'verbose_name_plural': 'Our Team',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('context', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('context', models.TextField()),
                ('image', models.ImageField(upload_to='equipments/')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Aminoacid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_what', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='aminoacids/')),
                ('manufacturer', models.CharField(max_length=150)),
                ('effect', models.TextField()),
                ('instruction', models.TextField()),
                ('advantages', models.TextField()),
                ('preparation', models.CharField(blank=True, max_length=200, null=True)),
                ('animal', models.ManyToManyField(related_name='aminoacids', to='core.animal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Amino Acid',
                'verbose_name_plural': 'Amino Acids',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CleaningProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_what', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('about', models.TextField()),
                ('structure', models.TextField()),
                ('usage', models.TextField()),
                ('packaging', models.CharField(blank=True, max_length=200, null=True)),
                ('animal', models.ManyToManyField(related_name='cleaning_products', to='core.animal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Cleaning Product',
                'verbose_name_plural': 'Cleaning Products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_what', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='foods/')),
                ('effect', models.TextField()),
                ('instruction', models.TextField()),
                ('packaging', models.CharField(blank=True, max_length=200, null=True)),
                ('animal', models.ManyToManyField(related_name='foods', to='core.animal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='paints/')),
                ('dosage', models.TextField()),
                ('animals', models.ManyToManyField(related_name='paints', to='core.animal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Paint',
                'verbose_name_plural': 'Paints',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.partner')),
            ],
            options={
                'verbose_name': 'Partner Image',
                'verbose_name_plural': 'Partner Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('for_what', models.CharField(blank=True, max_length=150, null=True)),
                ('structure', models.TextField()),
                ('image', models.ImageField(upload_to='vaccines/')),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('drug', models.TextField()),
                ('usage', models.TextField()),
                ('expiration_date', models.TextField()),
                ('storage', models.TextField()),
                ('animals', models.ManyToManyField(related_name='vaccines', to='core.animal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaryDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_what', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='drugs/')),
                ('structure', models.CharField(blank=True, max_length=150, null=True)),
                ('instruction', models.TextField()),
                ('dosage', models.TextField()),
                ('release_period', models.CharField(blank=True, max_length=10, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('animals', models.ManyToManyField(related_name='veterinary_drugs', to='core.animal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Veterinary Drug',
                'verbose_name_plural': 'Veterinary Drugs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VitaminsMinerals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_what', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='vitamins/')),
                ('effect', models.TextField()),
                ('dosage', models.TextField()),
                ('contraindications', models.TextField()),
                ('instruction', models.TextField()),
                ('packaging', models.CharField(blank=True, max_length=200, null=True)),
                ('animal', models.ManyToManyField(related_name='vitamins_minerals', to='core.animal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Vitamin/Mineral',
                'verbose_name_plural': 'Vitamins/Minerals',
                'ordering': ['title'],
            },
        ),
    ]
